<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HoneyDrunk.Identity.Abstractions\HoneyDrunk.Identity.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HoneyDrunk.Auth" Version="0.6.1" />
    <PackageReference Include="HoneyDrunk.Kernel" Version="0.8.1" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.23.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

<ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup></Project>
